# Generated by Django 4.2 on 2023-04-11 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='datetime',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='is_completed',
        ),
    ]
