# Generated by Django 4.2 on 2023-04-11 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_task_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_completed', 'created_at']},
        ),
    ]
